---
processes:
  - name: vector
    executable: /var/vcap/packages/vector/vector
    ephemeral_disk: true
    persistent_disk: false
    args:
      - --config=/var/vcap/jobs/vector/config/vector.toml
    limits:
      memory: <%= p("bpm.limits.memory") %>
      open_files: <%= p("bpm.limits.open_files") %>
      processes: <%= p("bpm.limits.processes") %>
    env: {}
    capabilities: []
