---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: src/vector
    contents:
      - path: .
        githubRelease:
          # https://github.com/timberio/vector
          slug: timberio/vector
          tag: v0.14.0
          disableAutoChecksumValidation: true
        includePaths:
          - vector-*-x86_64-unknown-linux-musl.tar.gz
