---
tags: {}

name: ((deployment_name))

releases:
  - name: bpm
    version: ((bpm_version))
    sha1: ((bpm_sha1))
    url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=((bpm_version))
  - name: syslog
    version: ((syslog_release_version))
    url: https://bosh.io/d/github.com/cloudfoundry/syslog-release?v=((syslog_release_version))
    sha1: ((syslog_release_sha1))
  - name: vector-boshrelease
    version: ((vector_boshrelease_version))
    url: https://github.com/aegershman/vector-boshrelease/releases/download/((vector_boshrelease_version))/vector-boshrelease-((vector_boshrelease_version)).tgz
    sha1: ((vector_boshrelease_sha1))

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm
  - name: syslog_forwarder
    jobs:
      - name: syslog_forwarder
        release: syslog
        properties:
          syslog:
            address: localhost
            port: 5514
            transport: tcp
            tls_enabled: false
          blackbox:
            log_filename: true

instance_groups:
  - name: vector
    azs: ((vector_azs))
    instances: ((vector_instances))
    vm_type: ((vector_vm_type))
    stemcell: default
    networks: [name: ((network))]
    jobs:
      - name: vector
        release: vector-boshrelease
        properties:
          vector_toml: ((vector_toml))

variables: []

stemcells:
  - alias: default
    os: ubuntu-bionic
    version: latest

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-5000
  update_watch_time: 1000-5000

features:
  randomize_az_placement: true
  use_dns_addresses: true
  use_short_dns_addresses: true
